version: "3.8"
services:
  server:
    build: .
    container_name: server_container
    command: ./server_program
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
